name: Git Push To Azure Devops
  # You may pin to the exact commit or the version.
  # uses: x-actions/git-push@fa7affbdc76b1c598c8337f9b830ea11c6d13d70
  uses: x-actions/git-push@v1
  with:
    # git user email
    GITHUB_EMAIL: ewer@outlook.com
    # git use username
    GITHUB_USERNAME: Ewerton
    # https:/<token>@github.com/owner/repo.git    tiutztyllspsxqzhva4drwbwxclann7rydfq4kcxfazy4epgpueq
    PUBLISH_REPO: https://ewernet.visualstudio.com/DefaultCollection/SyncTest/_git/SyncTest
    # git branch
    PUBLISH_BRANCH: master
    # dir to publish
    PUBLISH_DIR: # optional
